
linters:
  enable:
  - bodyclose
  - exportloopref
  - gochecknoinits
  - gocritic
  - gofmt
  - golint
  - misspell
  - prealloc
  - unconvert
  disable:
  - errcheck

issues:
  exclude-use-default: false
