name: lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  golangci-lint:
    name: golangci-lint

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: golangci/golangci-lint-action@v2
      with:
        version: v1.38

  go-mod-tidy:
    name: go-mod-tidy

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2

    - run: |
        go mod download
        go mod tidy
        git diff --exit-code
